#include <QByteArray>
#include <QRegularExpression>

#include "html2md.h"
#include "markdownparser.h"
#include "md4c-html.h"


const QByteArray templateArray =
        QByteArrayLiteral("<!DOCTYPE html>\n"
                          "<html>\n"
                          "<head>\n"
                          "<title>HTML generated by md4c</title>\n"
                          "</head>\n"
                          "<body class=\"preview\">\n");


void captureHtmlFragment (const MD_CHAR* data, MD_SIZE data_size, void* userData) {
    auto *array = static_cast<QByteArray*>(userData);

    array->append(data, data_size);
}

auto Parser::toHtml(const QString &in, const int dia) -> QString
{
    const QByteArray array = in.toUtf8(); // Use UTF-8 for better support
    QByteArray out = templateArray;
    out.reserve(array.size() *1.28 + 115);

    md_html(array.constData(), array.size(), &captureHtmlFragment, &out,
            MD_DIALECT_GITHUB, MD_HTML_FLAG_DEBUG);

    out.append("</body>\n"
               "</html>\n");
    out.squeeze();

    return QString::fromUtf8(out);
}

auto Parser::toMarkdown(const QString& in) -> QString
{
    return QString::fromStdString(html2md::Convert(in.toStdString()));
}
